" Vundle config
set rtp+=$HOME/vimfiles/bundle/Vundle.vim
call vundle#begin('$HOME/vimfiles/bundle/')
" Required:
Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-surround'
call vundle#end()

" Show block cursor on normal mode
let &t_ti.="\e[1 q"
let &t_SI.="\e[5 q"
let &t_EI.="\e[1 q"
let &t_te.="\e[0 q"

" General configs
:set number relativenumber
:set ignorecase
:set hlsearch

" Remap space as <leader>
nnoremap <SPACE> <Nop>
let mapleader=" "

" Custom configs
:imap jk <ESC>
:imap JK <ESC>
:nnoremap H ^
:nnoremap L $
:nnoremap J Lzz
:nnoremap K Hzz
:nnoremap <leader>j J
:nnoremap <leader>y yiw
:nnoremap <leader>Y yiW
:nnoremap <leader>p "0p
:nnoremap <leader>P "0P
:nnoremap <leader>r diw"0P

" <Ctrl-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>
